# Generated by Django 4.1.2 on 2022-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
