# Generated by Django 4.1.2 on 2022-10-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
